### ISSUE TITLE
The commands description in Usage.md

### ISSUE THREAD

**Issue by xiaohe27** [runtimeverification/javamop#175]
E.G, for the command: `javamop -agent [-n agentName] [-v] [-d <target directory>] <properties>` 

I'm not sure whether there exists a standard way of describing the command line arguments, but in the website http://docopt.org/ , I found they have slightly different meaning for the optional notation "[]".
According to the description on that website, [-n agentName] seems to be equivalent to [-n][agentName]. It also mentions that `--option ARG` is ambiguous because it can be either interpreted as an option followed by the option's argument or an option followed by a POSITIONAL argument (of the program).

They use parenthesis to disambiguate: `[(<one-argument> <another-argument>)]`
means either no argument or the two arguments go together.

I also notice that they use single '-' to denote the short option which has a single character (e.g. -n) while they use '--' followed by a string to denote long option (e.g. --agent). 

I don't think we need to follow their conventions strictly though, as long as it is clear to the users.

**Comment by seriousamlqz** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Qingzhou

Accept: https://www.linkedin.com/blink?simpleRedirect=0OdPoQd3wMdj8Nd38MejsRdPARfkh9rCZFt65QqnpKqipkqPB2cAFGu3RVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CgQbmNLp39IqjpFbjBApnxSrjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5975790255641489408_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=p3gJr6ZAcCNFdCAJemhBu7pJfmhFpioMkk92qAhns4x7qkRehSp2i5YOiSdcdj9zm4NOhCpytAB6pOR1jjBvgj1Wmntli3sJs5xGc6NhtDt4r4d5qP1ockFymmRHnS9kgjhxgz1cqmZLlkZ3p4MOiDF6q4EOlA9EgSoSm71xdDhPl6B9s7xEol9nl4cUiPlakT5JuD8PoDl8nSR1q2RDl4Zlqz9NhzlRlk51gnsPhSx5sCFzdRYShB51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CgQbmNLp39IqjpFbjBApnxSrjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5975790255641489408_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CgQbmNLp39IqjpFbjBApnxSrjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5975790255641489408_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
