### ISSUE TITLE
Proofread the usage doc of javamopagent

### ISSUE THREAD

**Issue by xiaohe27** [runtimeverification/javamop#192]
I wrote the usage doc for javamopagent sometime ago based on the current description of agent thing in javamop's usage doc. We want to keep all the desired features of the previous AgentGenerator, and ensure the new javamopagent is as robust and easy to use as the previous AgentGenerator in javamop.
 
Action: proofread the JavaMOPAgentUsage.md in https://github.com/runtimeverification/javamop/blob/agent/docs/JavaMOPAgentUsage.md,
and compare the behaviors of the agent generators of javamop's -agent option and javamopagent.

**Comment by owolabileg** [comment]
I made my changes as part of the [pull request](https://github.com/runtimeverification/javamop/pull/191). Closing this now, but feel free to re-open again if there is some issue with the changes I made, or if there is a new version of the documentation to be re-revised.
