### ISSUE TITLE
Test Javamop agent

### ISSUE THREAD

**Issue by xiaohe27** [runtimeverification/javamop#195]
@owolabileg, I modified your script so that it can test projects via agent generated by javamopagent now. The repository for the tests can be found at https://github.com/xiaohe27/JavaMOPAgent-Testing. 
I've tested projects No. 2-5, and the number of violations is the same as that in your report.
Currently, I found a project called `asterisk-java` where 148 violations were found, whereas it was reported to have 145 in your report.
@owolabileg, can you do some more tests until we find, say, 10 projects whose testing results conform to the report. That should be a good time to merge our agent branch.

@yzhang90 @kheradmand You are also welcome to have a test.

**Comment by owolabileg** [comment]
Well, as it is I ran your version of the script against projects in the list I gave you. I have more than 10 projects where the results match up. Some (like asterisk-java) are known to exhibit some non-determinism and so the count will differ from run to run. Just re-run that asterisk-java a few times and you'll see.

I don't have push access to the repo you created above. Let me know how you'd like to get the results.

I'm closing this for now. Please feel free to re-open if I missed something.
