### ISSUE TITLE
Does JavaMOP still accept directory containing .mop files as argument?

### ISSUE THREAD

**Issue by owolabileg** [runtimeverification/javamop#202]
It's possible that I missed some design decisions, but JavaMOP no longer seems to accept directories as argument:

```
1. git clone https://github.com/runtimeverification/javamop.git

2. mvn package

3. cd examples/agent/many/rvm

4. javamop -merge -keepRVFiles cfg

```

I get the following output:

```
String index out of range: -1
-Processing 0 specification(s)
null
```

Am I missing something? What is the current way to achieve the above? This is a blocker for me.

**Comment by pmeredit** [comment]
Since this seems to be getting no answers, I'll try to help as best I can.

What is that command line actually supposed to do?  We can probably write a
simple script to mimic it.

On Thu, Apr 23, 2015 at 5:01 AM, Owolabi Legunsen <notifications@github.com>
wrote:

> It's possible that I missed some design decisions, but JavaMOP no longer
> seems to accept directories as argument:
>
> 1. git clone https://github.com/runtimeverification/javamop.git
>
> 2. mvn package
>
> 3. cd examples/agent/many/rvm
>
> 4. javamop -merge -keepRVFiles cfg
>
>
> I get the following output:
>
> String index out of range: -1
> -Processing 0 specification(s)
> null
>
> Am I missing something? What is the current way to achieve the above? This
> is a blocker for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/runtimeverification/javamop/issues/202>.
>



-- 
-Patrick

**Comment by xiaohe27** [comment]
@owolabileg I'll take a look at this issue and try to solve it over the weekend.

**Comment by xiaohe27** [comment]
@owolabileg You can check my latest pull request and tell me how you would like to proceed.

**Comment by xiaohe27** [comment]
@owolabileg The problem you reported should have been solved; and I also added an integration test to make sure the feature of reading directory as input will not be affected unexpectedly in the future versions of JavaMOP.
