### ISSUE TITLE
JavaMOP4.0 binaries do not contain javamopagent tool

### ISSUE THREAD

**Issue by owolabileg** [runtimeverification/javamop#206]
I tried to install latest JavaMOP binaries from [here](http://fsl.cs.uiuc.edu/Download.php?filename=javamop-4.0.zip), as described in our current [INSTALL.md](https://github.com/runtimeverification/javamop/blob/master/INSTALL.md). Unfortutunately the /bin directory in that zip does not contain the ```javamopagent``` tool that one needs to build agents.

I can get around this by cloning javamop directly from github, but I asked a developer outside our team to follow our instructions and they got stomped on this.

**Comment by xiaohe27** [comment]
I made a new release. @kheradmand You maintained the our javamop's wiki page, right? Can you update the wiki page to track the latest release? I have added v4.1 and v4.2; we can show the v4.2 on the main download page and move all the remaining ones to the "All Versions" page.
