### ISSUE TITLE
We can no longer build JavaMOP Agents from our own properties :(

### ISSUE THREAD

**Issue by owolabileg** [runtimeverification/javamop#207]
If I try the following command with the latest version of JavaMOP:

```javamop -merge -keepRVFiles properties/annotated-java-api/java/util/```

I get error messages like the following:

```The mop name ServiceLoader_MultipleConcurrentThreads is not valid!```

There is nothing wrong with that property. After debugging, the error seems to be coming from this [line](https://github.com/runtimeverification/javamop/blob/master/src/main/java/javamop/JavaMOPMain.java#L353) where the regex we are using does not allow mop file names to have underscores in the middle; many of our properties have are named like: "*_*.mop"

**Comment by willschellhornrv** [comment]
This is a fix for the bug. I had to do it when I was using javamop in my own branch. 
https://github.com/runtimeverification/javamop/commit/5cc421028bb0e05c5b3ec5907a78a83e0d972742

I'll submit a javamop issue.

**Comment by xiaohe27** [comment]
@willschellhornrv @owolabileg  I made a little modification to that pull request.

**Comment by owolabileg** [comment]
The original error is now gone, but I still can't build an agent from our properties. Here are the steps that I followed with the latest JavaMOP and the errors I get:

1. ```git clone https://github.com/runtimeverification/property-db.git```
2. ```cd property-db/annotated-java-api```
3. ```javamop -merge -keepRVFiles java```
4. ```mkdir -p classes/mop```
5. ```rv-monitor -merge -d classes/mop/ `find -name "*.rvm"` ```
6. ```javamopagent MultiSpec_1MonitorAspect.aj classes -n JavaMOPAgent -v```

The 3 errors I get after step look like the following:

```
/home/owolabi/projects/rvtest/scripts/properties/annotated-java-api/MultiSpec_1MonitorAspect.aj:1 [error] Duplicate method ajc$if$4a16b97f(Object, JoinPoint.StaticPart, JoinPoint, JoinPoint.StaticPart, MultiSpec_1MonitorAspect) in type MultiSpec_1MonitorAspect
(no source information available)
```

**Comment by xiaohe27** [comment]
@owolabileg Thanks for the detailed error info. It seems that the problem has something to do with the generated code. I'll try to reproduce and debug this issue when I have time.

**Comment by xiaohe27** [comment]
@owolabileg I can reproduce the same problem with exactly the same 3 errors; I'll try to debug once I have time to do so.

**Comment by xiaohe27** [comment]
@owolabileg I narrowed down the range of specs causing the errors, and it turned out to be these three pointcuts:

```
pointcut Comparable_CompareToNull_nullcompare(Object o) : (call(* Comparable+.compareTo(..)) && args(o) && if(o == null)) && MOP_CommonPointCut();
	before (Object o) : Comparable_CompareToNull_nullcompare(o) {
		MultiSpec_1RuntimeMonitor.Comparable_CompareToNull_nullcompareEvent(o);
	}

	pointcut Comparable_CompareToNullException_badexception(Object o) : (call(* Comparable+.compareTo(..)) && args(o) && if(o == null)) && MOP_CommonPointCut();
	after (Object o) throwing (Exception e) : Comparable_CompareToNullException_badexception(o) {
		MultiSpec_1RuntimeMonitor.Comparable_CompareToNullException_badexceptionEvent(o, e);
	}


	pointcut Comparable_CompareToNullException_badcompare(Object o) : (call(* Comparable+.compareTo(..)) && args(o) && if(o == null)) && MOP_CommonPointCut();
	after (Object o) returning (int i) : Comparable_CompareToNullException_badcompare(o) {
		MultiSpec_1RuntimeMonitor.Comparable_CompareToNullException_badcompareEvent(o, i);
	}
```

**Comment by xiaohe27** [comment]
These three pointcuts are the same but with different names, so when they are put together, it will cause problems.

**Comment by xiaohe27** [comment]
@owolabileg Basically, the specs involved are two:
1. Comparable_CompareToNull.mop
2. Comparable_CompareToNullException.mop

Moreover, the first spec is good to run on itself, while the second spec, "Comparable_CompareToNullException.mop" cannot even be run by itself.

Combine these two specs to a single .aj file will therefore generate 3 pointcuts with same contents but different names, and as a result, causing the duplicate methods error.
