### ISSUE TITLE
javaMOP on Mac

### ISSUE THREAD

**Issue by lgundala** [runtimeverification/javamop#212]
I cannot get JavaMOP successfully installed on my mac machine. Where am i supposed add path and class path?

**Comment by xiaohe27** [comment]
How did you install JavaMOP on your mac machine? Are you using the binary distribution or building from source? Please refer to the Installation section of README. For the classpath setting, read the prerequisites of INSTALL.md file at the top level of JavaMOP's github page.

**Comment by lgundala** [comment]
am using binary distribution. when i run javamop on my machine, the following error shows up.
I have my $PATH:/Users/Amulya/Documents/javamop-4.2/bin
LAXMIs-MacBook-Pro:bin Amulya$ javamop
/Users/Amulya/Documents/javamop-4.2/bin/javamop: line 12: /Users/Amulya/Documents/javamop-4.2/bin/..//target/release/javamop/javamop/bin/javamop: No such file or directory

**Comment by xiaohe27** [comment]
Sorry, the link of the binary was wrong and pointed to the source code. The problem should have been fixed now.

**Comment by lgundala** [comment]
Thanx for the fix. I believe its updated in github also.
