### ISSUE TITLE
issues with javamop script

### ISSUE THREAD

**Issue by esherman77** [runtimeverification/javamop#213]
When I run javamop script from bin directory it gives me the following error:
$JavaMOPDir/javamop-4.2/bin/javamop: line 12: $JavaMOPDir/javamop-4.2/bin/..//target/release/javamop/javamop/bin/javamop: No such file or directory

So, what am I missing?

**Comment by owolabileg** [comment]
Did you follow these [instructions](https://github.com/runtimeverification/javamop/blob/master/INSTALL.md]) for installing JavaMOP? After what step did you see this error and on what platform are you running?

**Comment by esherman77** [comment]
Yes, I followed all instruction regarding adding jars to CLASSPATH and locations to PATH. I'm running on MacBook 10.9.5
Do we need to build JavaMOP? Because there is no binaries are provided with in the zip.

**Comment by xiaohe27** [comment]
Sorry, the link of the binary was wrong and pointed to the source code. The problem should have been fixed now.

**Comment by kheradmand** [comment]
The problem should be fixed now.
