### ISSUE TITLE
Random_OverrideNext property is broken

### ISSUE THREAD

**Issue by emopers** [runtimeverification/javamop#228]
The [Random_OverrideNext property](http://fsl.cs.illinois.edu/annotated-java/__properties/html/java/util/Random_OverrideNext.html) should only be violated if a subclass of `java.util.Random` does not override the `next(int bits)` method. Howerver, I have seen it violated in two perfectly legal scenarios, including [PassphraseBasedPRNG.java](https://github.com/tbuktu/ntru/blob/master/src/main/java/net/sf/ntru/encrypt/PassphraseBasedPRNG.java) which is a subclass of `java.util.Random` and clearly overrides `next(int bits)`. Can someone please explain this?

**Comment by xiaohe27** [comment]
The Random_OverrideNext property has a typo!
It used a wrong data type: it used Integer instead of int, for the data type of the parameter of the method next(int bits).

A quick fix is modifying the only statement in the try block.

Method nextmethod = klass.getDeclaredMethod("next", int.class);

**Comment by xiaohe27** [comment]
@emopers what do you think?

**Comment by emopers** [comment]
@xiaohe27 
Thanks for the feedback! That fix looks good for us
