### ISSUE TITLE
(Question) Interference on multiple executions

### ISSUE THREAD

**Issue by rbonifacio** [runtimeverification/javamop#264]
I am experimenting with JavaMOP by using a JUnit test suite. What is the best approach for "cleaning up" the state after a test run? My question is motivated because, as far as I observed, after executing a test case, it seems to me that the monitor does not reset (a test case is then interfering with the monitoring of a second test).

**Comment by owolabileg** [comment]
Hi @rbonifacio, thanks for your question. It's a little hard to diagnose this without seeing some concrete case. Is there a minimal repro step that you can share?

**Comment by rbonifacio** [comment]
Hi @owolabileg. Sorry for not providing sufficient details. 

Here is our specification:

https://github.com/helpmehelpus/MoniTests/blob/test-infrastructure/src/main/mop/MessageDigestSpec.mop

And here is one of our test cases: 

https://github.com/helpmehelpus/MoniTests/blob/test-infrastructure/src/test/java/MessageDigestTest.java

After running any of the test cases, I noticed that the monitor did not come back to an initial state. It seems to me that it is easy to solve this problem. My first trial was to call `__RESET` in the `@match` clause of the spec. I then realized that this is not a good idea because `@match` executes at every matched event (and not only when the complete sequence of expected events occurs), right?  

Please, let me know if you need more details. We are trying to improve the setup of our project, but it is still not that good. The README includes some instructions. 

https://github.com/helpmehelpus/MoniTests/tree/test-infrastructure

Many thanks for your attention.

**Comment by rbonifacio** [comment]
Hi @owolabileg. We are working on a Docker image for our project (this might help others reproduce our test cases). Before that, I reviewed our test case to expose our problem better. 

If we enable this test case here:

https://github.com/helpmehelpus/MoniTests/blob/71eba52208ea992d4eb440b1ab4204bd83306236/src/test/java/MessageDigestTest.java#L44-L51

This independent test case fails: 

https://github.com/helpmehelpus/MoniTests/blob/71eba52208ea992d4eb440b1ab4204bd83306236/src/test/java/MessageDigestTest.java#L23-L33

Keeping the "first" test case marked with the `@Ignore` annotation, this second one passes OK. 

The "ignored" test case violates the specification, while the second one does not. Nonetheless, after a violation, it looks like the monitor enters a state that prevents it from observing that the execution of the second test case is OK. 

In the `@fail` clause of the spec, we call the `__RESET` instruction. 

https://github.com/helpmehelpus/MoniTests/blob/71eba52208ea992d4eb440b1ab4204bd83306236/src/main/mop/MessageDigestSpec.mop#L43-L49

Thanks again.

**Comment by rbonifacio** [comment]
We already found and fixed our specifications. Thanks.
