### ISSUE TITLE
Test JavaMOP with Java 8

### ISSUE THREAD

**Issue by owolabileg** [runtimeverification/javamop#91]
We need to test JavaMOP with Java 8 on both Windows and Linux. When this is done, we should update the INSTALL.md file in the root directory.

**Comment by seriousamlqz** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Qingzhou

Accept: https://www.linkedin.com/blink?simpleRedirect=3sNdzcOczgNejcQcz0VdPkTejkZh4BKrSBQonhFtCVF9zdElDpIjP97fnBBiShBsC5EsOpQsSlRpRZBt6BSrCAZqSkConhzbmlQqnpKqiRQsSlRpORIrmkZpSVFqSdxsDgCpnhFtCV9pSlipn9Mfm4CoPoJr6hDcCNFdCAJuCNEs79xbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5975790270212505600_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6cSbmNApP9IqjpFbnFIq71OoiQZp6BB9Dt1gCVyu5ZIiARxpj9dt7BQt5p6llBKpCBPoQNUqkVnhRtfkldEq45DsSpepP1mq5hKhSpEozkOom94m4dEhBxzpmhfh3BlpDxDc7tSj3wTt3BbiiRzsR8Qojp8clFUlRcJoCZGcCRmoRpfhQZbqkFdsAMNkR9KpD0Mh55PpCZ6gkx7r4VfnT4Qm4hQt6R6dnllgk51knxznQVHiRkMjRF7kk4Zp6BLr2pQsSlRpRZBt6BSrCAZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCoPoJr6hDcCNFdCAJuCNEs79xbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5975790270212505600_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoipQsSlRpRZBt6BSrCAZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CoPoJr6hDcCNFdCAJuCNEs79xbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5975790270212505600_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
